config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get    '/resume',  to: 'home#resume'
  get    '/profile', to: 'home#profile'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :posts do
    resources :comments
  end
  resources :users

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  validates :name, presence: true

  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user, optional: true
  has_many   :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: { minimum: 3, maximum: 20 }
  validates :email, uniqueness: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/ }
  validates :password, presence: true
  validates :password_confirmation, presence: true

  has_many :posts, class_name: "Post"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    puts params
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @disable_nav = true
    @disable_foot = true
  end

  def resume
    @disable_foot = true
    @disable_resume = true
  end

  def profile
    puts "Mr. Templeton"
    @disable_foot = true
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    # puts "yo yo yo yo"
    # p params
    # puts "hiiiiiiiiii"
    # p post_params
    # puts "this is the current user: #{current_user.username}"
    fart = Post.new(post_params)
    fart.user_id = current_user.id
    fart.save!
    redirect_to '/posts'
  end

  private
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def show
    puts "this is the current user: #{current_user.username}"
    @user = User.find(params[:id])
    if current_user == @user
      @post = Post.new
    else
      redirect_to '/posts'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # def log_in(user)
  #   session[:user_id] = user.id
  # end
  #
  # def current_user=(user)
  #   @current_user = user
  # end
  #
  # def signed_in?
  #   !@current_user.nil?
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="headlineDiv"></div>

<h1 id="name">Matthew Jones</h1>
<p id="description"> junior full stack developer </p>

<div id="enterDiv"></div>
<h2 id="enter"><%= link_to 'enter', controller: 'posts'%></h2>

<video playsinline autoplay muted loop poster="<%= image_path "poster.png" %>" id="palms">
  <source src="<%= video_path "background.mp4" %>" type="video/mp4">
</video>

app/views/home/profile.html.erb
<div class="innerContainer"></div>

<div class="container">
  <div class="about">
    <h1 class="headline" id="headlineTop">Matt Jones</h1>

    <%= image_tag("IMG_5303.jpg", class: "aboutPhoto")%>

    <div class="aboutDeets">
      <p>Welcome to my site built with Ruby on Rails, I'm Matthew Jones. I built this site in order to showcase some skills I mastered while studying at Dev Bootcamp, such as the video background on the landing page (filmed in slo-mo, I wouldn't blame ya if you didn't notice).</p>
      <p>Dev Bootcamp taught me a lot more than just coding, databases, or object-oriented design.  DBC employs a paired-programming environment; with a new partner each day, I quickly learned how to communicate and work well with classmates from a variety of backgrounds.</p>
      <p>I believe communication, working smart, and clean code are critical to success. I am looking to work in an environment with mentoring, code reviews, and strong communication.</p>
      <p>30 Rock is my favorite show, I've watched every episode about 30 times, except the finale, I've never watched it.  My TV habit includes high brow shows like Homeland, The Good Fight, Game of Thrones and Westworld.... and low brow shows like Vanderpump Rules, the Housewives, and UnREAL.</p>
    </div>
  </div>
</div>


<div class="container">
  <div class="about">
    <h1 class="headline" id="headlineTop">Gunner</h1>

    <%= image_tag("IMG_0013.jpg", class: "aboutPhoto")%>

    <div class="aboutDeets">
      <p>This mini horse is the reason I get out of bed in the mornings.... and sometimes the reason I don't.</p>
      <p>Born July 22, 2015, this Great Dane is a curious and troublemaking cutie.  Weighing in at about 154lbs, this pup needs a lot of love, and food.</p>
      <p>Recently hospitalized for eating an excessive amount of grass, everything about this dog is expensive.  Don't worry, he's recovering well, and feeling much better.</p>
      <p>Now that we live on over an acre in Fallbrook, this guy loves to smell flowers and stare into the wind.  He does not know how to swim, and has no interest in learning.</p>
      <p>There's a 75% chance he is currently sleeping at any given time.</p>
    </div>
  </div>
</div>


<div class="container">
  <div class="about">
    <h1 class="headline" id="headlineTop">Sarge</h1>

    <%= image_tag("IMG_0154.jpg", class: "aboutPhoto")%>

    <div class="aboutDeets">
      <p>Half Great Dane, and half Labrador Retriever, we refer to this guy as a Lab XL, or a Pretty Good Dane.</p>
      <p>Adopted from a Great Dane Rescue Center, Sarge was dropped off when his first family found out he wasn't a purebred Dane.</p>
      <p>Sargie has the best feautures of each breed, he loves to follow his people wherever we go, including in the pool.</p>
      <p>A naturally pretty lazy dog, Sarge is likely half-asleep at this very moment.</p>
      <p>Sarge is about 10 years old.</p>
      <p>And is also allergic to chicken.</p>
      <p>but looooves it</p>
    </div>
  </div>
</div>

<p></p>

app/views/home/resume.html.erb
<iframe src="https://www.dropbox.com/s/ws7rj31rvgdzqhv/Resume%20-%20Jr.%20Developer.pdf?raw=1" class="resume" frameborder="0"></iframe>

app/views/layouts/_footer.html.erb
<div class="footbar">
  <% if user_signed_in? %>
    <p class="footbarText" id="footbarProfile"><%= link_to 'profile', user_path(current_user) %></p>
    <p class="footbarText" id="footbarLogout"><%= link_to 'logout', destroy_user_session_path, method: :delete %></p>
  <% else %>
    <p class="footbarText" id="footbarLogin"><%= link_to 'admin login', new_user_session_path %></p>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="fixbar" id="main"></div>

<div class="fixbar" id="blur"></div>

<p class="fixbarText" id="fixbarProfile"><%= link_to 'about matth3wjones', profile_path %></p>
<p class="fixbarText" id="fixbarLogo"><%= link_to 'projects ', controller: '/posts' %></p>

<% if @disable_resume %>
  <p class="fixbarText" id="fixbarRésuméorBlog"><%= link_to 'blog', controller: '/posts'%></p>
<% else %>
  <p class="fixbarText" id="fixbarRésuméorBlog"><%= link_to 'résumé', resume_path %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' unless @disable_nav %>
    <%= yield %>
    <%= render 'layouts/footer' unless @disable_foot %>
  </body>
</html>

app/views/posts/index.html.erb
<h1 class="headline">Matt's Latest Projects</h1>

<div class="innerContainer"></div>

<div class="container">
  <div class="postContainer">
    <% @posts.reverse_each do |post| %>
      <div class="post">
        <div class="postTitle"><%= link_to "#{post.title}", post_path(post.id) %></div>
        <div class="postAbsoluteTop postAuthor">Author: </div>
        <div class="postAbsoluteTop authorName"><%=post.user.username%></div>
        <% if post.image.exists? %>
          <div class="postImage"><%=image_tag post.image.url(:medium)%></div>
        <% end %>
        <div class="postDescription"><%=post.description%></div>
        <div class="postAbsoluteBottom commentCount"><%=post.comments.count%></div>
        <div class="postAbsoluteBottom postComment"> Comments</div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1 class="headline"><%= @post.title %></h1>

<div class="innerContainer"></div>

<div class="post showPost">
  <div class="postAbsoluteTop postAuthor">Author: </div>
  <div class="postAbsoluteTop authorName"><%=@post.user.username%></div>
  <% if @post.image.exists? %>
   <div class="postImage"><%=image_tag @post.image.url(:large)%></div>
  <% end %>
  <div class="postDescription"><%=@post.description%></div>
</div>

<div class="showComments">

  <% @post.comments.each do |comment| %>
    <div class="displayComment">
      <div class="postAbsoluteTop postAuthor">Author: </div>
      <div class="postAbsoluteTop authorName"><%=comment.name%></div>
      <%=comment.text%>
    </div>
  <% end %>

  <div class="displayComment newComment">

    <%= form_for([@post, @post.comments.build]) do |f| %>
      <div class="formContainerComment">
        <div class="formEntryContainer">
          <%= f.label :name, class: "name" %>
          <%= f.text_field :name, placeholder: "enter your name", id: "name" %><br>
        </div>

        <div class="formEntryContainer">
          <%= f.label :text, class: "text" %>
          <%= f.text_area :text, placeholder: "add a comment", id: "text" %>
        </div>
      </div>
      <%= button_tag "Submit", class: "submit" %>
    <% end %>

  </div>
</div>

app/views/users/login.html.erb
<h1 class="headline">Log in</h1>

<div class="container">
  <div class="innerContainer">
    <div class="loginContainer">
      <%= form_for(@user) do |f| %>
        <div class="loginForm">
          <%= f.label :username, id: "username" %>
          <%= f.text_field :username, placeholder: "enter username", class: "field", id: "usernameField" %><br>

          <%= f.label :password, id: "password" %>
          <%= f.password_field :password, placeholder: "enter password", class: "field", id: "passwordField" %><br>
        </div>
        <%= button_tag "Submit", class: "submit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="headline"><%=@user.username%></h1>

<div class="innerContainer"></div>

<div class="newPost">
  <p class="postTitle">Add a New Post</p>
  <%= form_for(@post) do |f| %>
    <div class="formContainer">
      <div class="formEntryContainer">
        <%= f.label :title, class: "title" %>
        <%= f.text_field :title, placeholder: "enter title", id: "title" %><br>
      </div>
      <div class="formEntryContainer">
        <%= f.label :description, class: "description" %>
        <%= f.text_area :description, placeholder: "enter description", id: "description" %>
      </div>
      <div class="formEntryContainer">
        <%= f.label :image, class: "image" %>
        <%= f.file_field :image, id: "chooseImage" %>
      </div>
    </div>
    <%= button_tag "Submit", class: "submit" %>
  <% end %>
</div>